[2023-11-08 17:59:17] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn a8bf0301daea77e3 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:59:17] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn a8bf0301daea77e3 127.0.0.1:63141 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:59:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-08 17:59:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20133: connect: connection refused
[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-08 17:59:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-08 17:59:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20132: connect: connection refused
