[2023-11-08 17:43:17] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn d39ada8946107d90 127.0.0.1:61342 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:43:17] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn d39ada8946107d90 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:43:49] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn d39ada8946107d90 127.0.0.1:61439 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:43:49] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn d39ada8946107d90 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
